language: go
go:
- master
env:
  matrix:
    secure: LK/8UxB21vbGOk5sPLEZOHWiyYNnEk5/FymVfDYnDARxGXReIY1ZNuzgSB2ot92uFJI2YvxDjxGLxB8MMlqMbsj41zJrxX+1bsiCdNuHu9BMygENM/lify2S8nSZCMdWSgQleiWHtFLSYKQnPN1jVvXZCuxqs+rYHso84GYmPzHiwwC4rc2prcb4jJsSTrt2P+EEPoHT9JBhIAkUp5vnBUAmijuuNbP+THg9SLLhjTTXq8E7TkQT2I1uBWUBO400UeV5VvHrOAOVshXDOwkE9ogoyfsZjb8ZuLSLLwoJ65E1npFMkxJSKBy7WUAO2vpHhTlqCASv5dwXIUMVB7A0bL7AeTlihwBuCcCmfYnA1Dljaw+9ZYxYa6lFIuIT8MaRGAh6m/4mYHFq5yOLQH5AvJX5eXBc3uPBvfqbvtCxRUUZXfGrS/adWFpuplZCPcw8RdLznmQZckk1DzudXHihS4JmPGRKjC8Tt+5nRnIWLVow5H1/zcRXIcDHfJB3xlJIIFLD5Tx9zkW10rkMZbi1x07a9g9yiDzJFUPmg9fm/IzVELvbHQa3sjyva0SMz38be7+v2WfMUQcJvmOZnFNUPy5NiSJAVKx+gAEooJfDQ/bg6ntGFfZm266uNQRYzckJciJIhSVeV0oPl+Pz16k3Mo7fl7xvyRoakMmLVZODu/I=
